# Generated by Django 5.0.6 on 2025-12-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MQ135Reading',
        ),
    ]
